name: iosApp
options:
  bundleIdPrefix: com.aditlal
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"

settings:
  base:
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
    info:
      path: iosApp/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        CADisableMinimumFrameDurationOnPhone: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleName: "Lumen Sample"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aditlal.sample
        SWIFT_VERSION: "5.0"
        FRAMEWORK_SEARCH_PATHS: "$(SRCROOT)/../sample/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)"
        OTHER_LDFLAGS: "$(inherited) -framework SampleApp"
    preBuildScripts:
      - name: "Build Kotlin Framework"
        script: |
          cd "$SRCROOT/.."
          ./gradlew :sample:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false
